import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  /**
   * Next 16 writes an AGENTS.md and a CLAUDE.md into the project root on every
   * `next dev`. Both are forbidden here: the Hackathon tree contract allows
   * exactly one doc file per level (CLAUDE.md, generated by `hack docs`) and no
   * AGENTS.md anywhere. Leaving this on would silently recreate them after
   * every dev run.
   */
  agentRules: false,

  /**
   * https://mochi.edycu.dev is GitHub Pages — static files only, no Node
   * runtime, no API routes. `output: 'export'` makes `next build` emit a fully
   * static `out/` directory instead. The site is served at the domain root
   * (not a subpath), so no basePath/assetPrefix is needed.
   */
  output: "export",
};

export default nextConfig;
