import type { NextConfig } from "next";
import { readFileSync } from "node:fs";

/**
 * The released version shown in the footer.
 *
 * In CI, `.github/workflows/pages.yml` resolves the newest release tag from the
 * GitHub API and passes it in. It has to come from the API rather than from
 * package.json: Pages builds off the CI run for the FEATURE commit, which is
 * before semantic-release has bumped anything, so the file on disk at build
 * time is always the previous release and the site would sit a version behind.
 *
 * The package.json read below is the local-development fallback only — running
 * `next dev` should show something honest rather than "undefined".
 *
 * Deliberately not a shields.io badge: this page ships no remote images, and a
 * version number is not worth becoming the first one.
 */
const { version: localVersion } = JSON.parse(
  readFileSync(new URL("../package.json", import.meta.url), "utf8"),
) as { version: string };

const version = process.env.NEXT_PUBLIC_APP_VERSION || localVersion;

const nextConfig: NextConfig = {
  env: {
    NEXT_PUBLIC_APP_VERSION: version,
  },

  /**
   * Next 16 writes an AGENTS.md and a CLAUDE.md into the project root on every
   * `next dev`. Both are forbidden here: the Hackathon tree contract allows
   * exactly one doc file per level (CLAUDE.md, generated by `hack docs`) and no
   * AGENTS.md anywhere. Leaving this on would silently recreate them after
   * every dev run.
   */
  agentRules: false,

  /**
   * https://mochi.edycu.dev is GitHub Pages — static files only, no Node
   * runtime, no API routes. `output: 'export'` makes `next build` emit a fully
   * static `out/` directory instead. The site is served at the domain root
   * (not a subpath), so no basePath/assetPrefix is needed.
   */
  output: "export",
};

export default nextConfig;
