import type { NextConfig } from "next";
import { readFileSync } from "node:fs";

/**
 * The released version, read from the repository root's package.json at build
 * time.
 *
 * That file is the one semantic-release bumps, so it is always the same number
 * as the newest GitHub release tag — reading it here means the footer chip
 * cannot drift from the release the site was actually built from. Deliberately
 * NOT a shields.io badge: this page ships no remote images, and a version
 * number is not worth becoming the first one.
 */
const { version } = JSON.parse(
  readFileSync(new URL("../package.json", import.meta.url), "utf8"),
) as { version: string };

const nextConfig: NextConfig = {
  env: {
    NEXT_PUBLIC_APP_VERSION: version,
  },

  /**
   * Next 16 writes an AGENTS.md and a CLAUDE.md into the project root on every
   * `next dev`. Both are forbidden here: the Hackathon tree contract allows
   * exactly one doc file per level (CLAUDE.md, generated by `hack docs`) and no
   * AGENTS.md anywhere. Leaving this on would silently recreate them after
   * every dev run.
   */
  agentRules: false,

  /**
   * https://mochi.edycu.dev is GitHub Pages — static files only, no Node
   * runtime, no API routes. `output: 'export'` makes `next build` emit a fully
   * static `out/` directory instead. The site is served at the domain root
   * (not a subpath), so no basePath/assetPrefix is needed.
   */
  output: "export",
};

export default nextConfig;
